# -*- coding: utf-8 -*-
"""1_DOCTOR DATA  TEST VERSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124kRm1YBipHsH_jji0ex4rf1v5rnNvGM

#DOCTORS DATA ANALYSIS
"""

!pip install openpyxl -q

# Upload your CSV file
from google.colab import files
uploaded = files.upload()

# Cell 2: Import Libraries
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

df = pd.read_csv('doctors_data_final.csv')
print(f"📊 Loaded {len(df)} doctor records")
print(f"📋 Columns: {', '.join(df.columns)}")
print("\n" + "="*80)
df.head()

unique_designations = df['designation'].unique()
display(unique_designations)



"""#Load Data"""



unique_qualifications = df['qualifications'].unique()
display(unique_qualifications)





filtered_profiles = df[df['hospital'].isna() & \
                         df['name'].notna() & \
                         df['qualifications'].notna() & \
                         df['specialty'].notna() & \
                         df['experience'].notna() & \
                         df['location'].notna()]
display(filtered_profiles)

nan_hospitals = df[df['hospital'].isna()]
display(nan_hospitals)

df = df.drop(columns=['designation'])
print(" 'designation' column removed successfully.")
display(df.head())

bmdc_qualifications = [q for q in unique_qualifications if isinstance(q, str) and q.startswith('BMDC')]
display(bmdc_qualifications)

nan_hospital_count = df['hospital'].isna().sum()
print(f"Number of NaN values in 'hospital' column: {nan_hospital_count}")

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

nan_hospitals = df[df['hospital'].isna()]
display(nan_hospitals)