# -*- coding: utf-8 -*-
"""4_Bangladeshi and Indian Doctors(CLEANED).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVYVsE7qWuogKUyqg3oWhKSb3bzs8Okv
"""



from google.colab import files
import pandas as pd
import io

# Upload a CSV file
uploaded = files.upload()

# Check if any file was uploaded
if uploaded:
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}"')
        # Read the uploaded CSV file into a pandas DataFrame
        df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
        print("File loaded into DataFrame successfully.")
        # Display the first 5 rows of the DataFrame
        display(df.head())
else:
    print("No file uploaded.")

print('Checking for NaN values in columns (excluding designation):')
for column in df.columns:
    if column != 'designations': # Assuming 'designations' was the column meant, based on head() output
        nan_count = df[column].isnull().sum()
        if nan_count > 0:
            print(f"Column '{column}': {nan_count} NaN values")
        else:
            print(f"Column '{column}': No NaN values")

import pandas as pd

# load your file
# Corrected filename from 'doctors.csv' to 'Bangladeshi and Indian Doctors.csv'
df = pd.read_csv("2Bangladeshi and Indian Doctors - Copy.csv")

# If the 'experience' column exists:
if "experience" in df.columns:

    # Move values only where main column is empty/NaN
    df["experience(IN YEARS OVERALL)"] = df["experience(IN YEARS OVERALL)"].fillna(df["experience"])

    # Optionally drop the wrong column
    df = df.drop(columns=["experience"])

# save cleaned file
df.to_csv("doctors_cleaned.csv", index=False)

print('Checking for NaN values in columns (excluding designation):')
for column in df.columns:
    if column != 'designations': # Assuming 'designations' was the column meant, based on head() output
        nan_count = df[column].isnull().sum()
        if nan_count > 0:
            print(f"Column '{column}': {nan_count} NaN values")
        else:
            print(f"Column '{column}': No NaN values")

nan_specialty_profiles = df[df['specialty'].isnull()]
display(nan_specialty_profiles)

unique_qualifications_nan_specialty = nan_specialty_profiles['qualifications'].unique()
for qual in unique_qualifications_nan_specialty:
    print(qual)

# Define the string to be removed
string_to_remove = "Domiciliary Services, Find Doctor, "

# Apply the replace operation to the 'qualifications' column
df['qualifications'] = df['qualifications'].str.replace(string_to_remove, '', regex=False)

print("Qualifications cleaned. Displaying a sample of unique qualifications from profiles with NaN specialty:")
# Re-display unique qualifications from profiles with NaN specialty to show the effect
nan_specialty_profiles_cleaned = df[df['specialty'].isnull()]
unique_qualifications_nan_specialty_cleaned = nan_specialty_profiles_cleaned['qualifications'].unique()
for qual in unique_qualifications_nan_specialty_cleaned:
    print(qual)

print("\nFirst 5 rows of the DataFrame after qualifications cleaning:")
display(df.head())

import re

# Function to extract only numbers from the experience string
def extract_numeric_experience(experience_str):
    if pd.isna(experience_str):
        return None
    # Use regex to find all digits
    match = re.search(r'\d+', str(experience_str))
    if match:
        return float(match.group(0))
    return None

# Apply the function to the 'experience(IN YEARS OVERALL)' column
df['experience(IN YEARS OVERALL)'] = df['experience(IN YEARS OVERALL)'].apply(extract_numeric_experience)

# Display the first 5 rows to show the cleaned column
print("First 5 rows of the DataFrame after cleaning 'experience(IN YEARS OVERALL)':")
display(df.head())

# Display updated NaN counts for the column
print("\nUpdated NaN count for 'experience(IN YEARS OVERALL)':")
print(df['experience(IN YEARS OVERALL)'].isnull().sum())

country_names = [
    'Bangladesh', 'India'
]

# Iterate through the DataFrame to fill missing 'country' values
for index, row in df[df['country'].isnull()].iterrows():
    location = str(row['location'])
    for country in country_names:
        if country in location:
            df.loc[index, 'country'] = country
            break # Assign the first found country and move to the next row

print("Updated NaN count for 'country' column:")
print(df['country'].isnull().sum())

print("\nFirst 5 rows of the DataFrame after filling 'country' from 'location':")
display(df.head())

print('Checking for NaN values in columns (excluding designation):')
for column in df.columns:
    if column != 'designations': # Assuming 'designations' was the column meant, based on head() output
        nan_count = df[column].isnull().sum()
        if nan_count > 0:
            print(f"Column '{column}': {nan_count} NaN values")
        else:
            print(f"Column '{column}': No NaN values")

nan_location_profiles = df[df['hospital'].isnull()]
display(nan_location_profiles)

# Identify profiles with NaN in 'hospital' column
hospital_nan_indices = df[df['hospital'].isnull()].index

# Fill 'hospital' for these profiles
df.loc[hospital_nan_indices, 'hospital'] = 'Rainbow Children Heart Institute | Hyderabad'

# Fill 'location' for these profiles
df.loc[hospital_nan_indices, 'location'] = 'Plot No, 22, Road No. 10, Avenue 4, Banjara Hills, Hyderabad, Telangana, India, Hyderabad-500034, India'

# Fill 'country' for these profiles
df.loc[hospital_nan_indices, 'country'] = 'India'

print("Updated profiles originally with NaN 'hospital' values:")
# Display the profiles that were just updated
display(df.loc[hospital_nan_indices])

print("\nUpdated NaN counts for relevant columns:")
nan_counts_after_update = df[['hospital', 'location', 'country']].isnull().sum()
display(nan_counts_after_update)

print('Checking for NaN values in columns (excluding designation):')
for column in df.columns:
    if column != 'designations': # Assuming 'designations' was the column meant, based on head() output
        nan_count = df[column].isnull().sum()
        if nan_count > 0:
            print(f"Column '{column}': {nan_count} NaN values")
        else:
            print(f"Column '{column}': No NaN values")

nan_location_profiles = df[df['location'].isnull()]
display(nan_location_profiles)



import pandas as pd

# Create a dictionary mapping indices to their specific locations
location_updates = {
    2627: 'C.I.T Scheme, Gariahat Rd, Dhakuria, LXXII Block A, P-4 & 5, Kolkata, West Bengal, Kolkata-700029, India',
    2572: 'Kirloskar Business Park, Bellary Road, Bangalore-560024, India',
    2553: '45/1, 45th Cross, Jayanagar 9th Block, Bangalore-560069, India',
    2542: 'Dr. E Borges Road, Dona Paula, Panaji, Goa, Bangalore-403004, India',
    2494: 'JC-16 & 17, Salt Lake City, Sector-3, Kolkata-700106, India',
    2476: 'Kirloskar Business Park, Bellary Road, Bangalore-560024, India',
    2301: 'Kirloskar Business Park, Bellary Road, Bangalore-560024, India',
    2208: 'Kirloskar Business Park, Bellary Road, Bangalore-560024, India'
}

# Iterate through the dictionary and update the DataFrame
for index, loc in location_updates.items():
    df.loc[index, 'hospital'] = 'Manipal Hospitals'
    df.loc[index, 'country'] = 'India'
    df.loc[index, 'location'] = loc

print("Updated profiles:")
# Display the profiles that were just updated
display(df.loc[list(location_updates.keys())])

print("\nUpdated NaN counts for relevant columns:")
nan_counts_after_update_specific = df[['hospital', 'location', 'country']].isnull().sum()
display(nan_counts_after_update_specific)

nan_location_profiles = df[df['location'].isnull()]
display(nan_location_profiles)



import pandas as pd

# Define the updates for hospital, location, and country for the specified indices
updates = {
    2180: {
        'hospital': 'Sagar Hospitals- DSI',
        'location': 'Banashankari Behind DSI campus, Shavige Malleshwara Hills, Kumaraswamy Layout, Bengaluru- 560 078 Karnataka, India, Bangalore-560078, India',
        'country': 'India'
    },
    2283: {
        'hospital': 'Peerless Hospital',
        'location': '360 Panchasayar, Kolkata, West Bengal, Kolkata-700094, India',
        'country': 'India'
    },
    2344: {
        'hospital': 'Vivacity Multispeciality Hospital',
        'location': '23, Jessore Rd, Burimar Bagan, Madhyamgram, Kolkata, West Bengal, Kolkata-700129, India',
        'country': 'India'
    },
    2547: {
        'hospital': 'Vivacity Multispeciality Hospital',
        'location': '23, Jessore Rd, Burimar Bagan, Madhyamgram, Kolkata, West Bengal, Kolkata-700129, India',
        'country': 'India'
    },
    2599: {
        'hospital': 'Jaypee Hospital',
        'location': 'Jaypee Hospital Rd, Goberdhanpur, Sector 128, Noida-201304, India',
        'country': 'India'
    }
}

# Apply the updates to the DataFrame
for index, data in updates.items():
    df.loc[index, 'hospital'] = data['hospital']
    df.loc[index, 'location'] = data['location']
    df.loc[index, 'country'] = data['country']

print("Updated profiles:")
# Display the profiles that were just updated
display(df.loc[list(updates.keys())])

print("\nUpdated NaN counts for relevant columns:")
nan_counts_after_specific_update = df[['hospital', 'location', 'country']].isnull().sum()
display(nan_counts_after_specific_update)



import pandas as pd

# Define the updates for hospital, location, and country for the specified indices
updates_final = {
    2606: {
        'hospital': 'DESUN Hospital',
        'location': 'Desun More, 720, Eastern Metropolitan Byp Rd, Golpark, Sector I, Kasba,, Kolkata-700107, India',
        'country': 'India'
    },
    2617: {
        'hospital': 'DESUN Hospital',
        'location': 'Desun More, 720, Eastern Metropolitan Byp Rd, Golpark, Sector I, Kasba,, Kolkata-700107, India',
        'country': 'India'
    },
    2653: {
        'hospital': 'DESUN Hospital',
        'location': 'Desun More, 720, Eastern Metropolitan Byp Rd, Golpark, Sector I, Kasba,, Kolkata-700107, India',
        'country': 'India'
    }
}

# Apply the updates to the DataFrame
for index, data in updates_final.items():
    df.loc[index, 'hospital'] = data['hospital']
    df.loc[index, 'location'] = data['location']
    df.loc[index, 'country'] = data['country']

print("Updated profiles:")
# Display the profiles that were just updated
display(df.loc[list(updates_final.keys())])

print("\nUpdated NaN counts for relevant columns:")
nan_counts_final_update = df[['hospital', 'location', 'country']].isnull().sum()
display(nan_counts_final_update)

import pandas as pd
from google.colab import files

# Define the filename for the output CSV file
output_csv_filename = 'bd_ind_doc.csv'

# Save the DataFrame to a CSV file
df.to_csv(output_csv_filename, index=False)

# Provide a link to download the file
files.download(output_csv_filename)

print(f"The cleaned DataFrame has been saved to '{output_csv_filename}' and is available for download.")

print('Checking for NaN values in columns (excluding designation):')
for column in df.columns:
    if column != 'designations': # Assuming 'designations' was the column meant, based on head() output
        nan_count = df[column].isnull().sum()
        if nan_count > 0:
            print(f"Column '{column}': {nan_count} NaN values")
        else:
            print(f"Column '{column}': No NaN values")

nan_location_profiles = df[df['specialty'].isnull()]
display(nan_location_profiles)

nan_location_profiles = df[df['experience(IN YEARS OVERALL)'].isnull()]
display(nan_location_profiles)
nan_location_profiles.count()

nan_location_profiles = df[df['specialty'].isnull()]
display(nan_location_profiles)

import numpy as np

# Create a dictionary mapping indices to their specific specialties
specialty_updates_further = {
    2556: 'Internal Medicine Specialist',
    2602: 'Internal Medicine Specialist',
    2648: 'Physical Medicine & Rehabilitation Specialist'
}

# Iterate through the dictionary and update the DataFrame
for index, specialty in specialty_updates_further.items():
    df.loc[index, 'specialty'] = specialty

print("Updated profiles:")
# Display the profiles that were just updated
display(df.loc[list(specialty_updates_further.keys())])

print("\nUpdated NaN count for 'specialty' column:")
print(df['specialty'].isnull().sum())

import numpy as np

# Create a dictionary mapping indices to their specific specialties
specialty_updates = {
    2161: 'Paediatric Cardiac Surgeon',
    2179: 'Anaesthesiology',
    2199: 'Oncology',
    2210: 'Obstetrics & Gynaecology',
    2211: 'Orthopaedic Surgeon',
    2221: 'Gastroenterology',
    2231: 'Plastic Surgeon',
    2241: 'Cardiologist',
    2246: 'Dermatologist',
    2261: 'Plastic Surgeon',
    2282: 'Oncology',
    2285: 'Plastic Surgeon',
    2296: 'Dermatologist',
    2324: 'Dermatologist',
    2330: 'Gastroenterology',
    2340: 'Orthopaedics',
    2347: 'Neurologist',
    2355: 'Neurologist',
    2365: 'Neurologist',
    2375: 'Neurologist',
    2380: 'Cardiology',
    2386: 'Cardiology',
    2389: 'Cardiology',
    2395: 'Cardiology',
    2402: 'Cardiology',
    2411: 'Cardiology',
    2421: 'Cardiology',
    2430: 'Cardiology',
    2440: 'Cardiology',
    2449: 'Cardiology',
    2457: 'Cardiology',
    2466: 'Cardiology',
    2475: 'Paediatric Cardiac Surgeon',
    2485: 'Orthopaedics',
    2493: 'Nephrology',
    2504: 'Nephrology',
    2514: 'Paediatrician',
    2524: 'Paediatrician',
    2533: 'Paediatrician',
    2541: 'Paediatrician',
    2552: 'Nephrology',
    2561: 'Neurology',
    2571: 'Neurology',
    2580: 'Neurology',
    2589: 'Neurology',
    2600: 'Nephrology',
    2608: 'Nephrology',
    2616: 'Nephrology',
    2626: 'Nephrology',
    2635: 'Nephrology',
    2644: 'Nephrology',
    2652: 'Nephrology'
}

# Iterate through the dictionary and update the DataFrame
for index, specialty in specialty_updates.items():
    df.loc[index, 'specialty'] = specialty

print("Updated profiles originally with NaN 'specialty' values:")
# Display the profiles that were just updated
display(df.loc[list(specialty_updates.keys())])

print("\nUpdated NaN counts for 'specialty' column:")
print(df['specialty'].isnull().sum())

nan_location_profiles = df[df['specialty'].isnull()]
display(nan_location_profiles)

import numpy as np

# Identify the indices of the rows where 'specialty' is NaN
nan_specialty_indices = df[df['specialty'].isnull()].index

# Create a dictionary mapping indices to their specific specialties based on qualifications
remaining_specialty_updates = {
    2166: 'ENT Specialist',
    2169: 'ENT Specialist',
    2183: 'Internal Medicine Specialist',
    2187: 'Internal Medicine Specialist',
    2200: 'Internal Medicine Specialist',
    2201: 'General Medicine',
    2222: 'Anaesthesiologist',
    2225: 'ENT Specialist',
    2229: 'ENT Specialist',
    2235: 'Internal Medicine Specialist',
    2251: 'Neurosurgeon',
    2252: 'General Medicine',
    2258: 'Neurosurgeon',
    2266: 'General Medicine',
    2325: 'Internal Medicine Specialist',
    2328: 'ENT Specialist',
    2333: 'General Medicine',
    2334: 'Physical Medicine & Rehabilitation Specialist',
    2348: 'ENT Specialist',
    2412: 'Physical Medicine & Rehabilitation Specialist',
    2418: 'Physical Medicine & Rehabilitation Specialist',
    2453: 'General Practitioner',
    2473: 'General Medicine',
    2486: 'General Practitioner',
    2512: 'Internal Medicine Specialist',
    2556: 'Internal Medicine Specialist',
    2602: 'Internal Medicine Specialist',
    2648: 'Physical Medicine & Rehabilitation Specialist'
}

# Iterate through the dictionary and update the DataFrame
for index, specialty in remaining_specialty_updates.items():
    df.loc[index, 'specialty'] = specialty

print("Updated profiles with remaining NaN 'specialty' values:")
# Display the profiles that were just updated
display(df.loc[list(remaining_specialty_updates.keys())])

print("\nUpdated NaN count for 'specialty' column:")
print(df['specialty'].isnull().sum())

nan_location_profiles = df.isnull()
display(nan_location_profiles)

nan_counts = df.isnull().sum()
columns_with_nan = nan_counts[nan_counts > 0]

if not columns_with_nan.empty:
    print('Columns with NaN values:')
    print(columns_with_nan)
else:
    print('No columns with NaN values found.')

nan_experience_profiles = df[df['experience(IN YEARS OVERALL)'].isnull()]
display(nan_experience_profiles)

import pandas as pd
pd.set_option('display.max_colwidth', None)
display(nan_experience_profiles['profile_url'])

print("Summary of profiles with NaN 'experience(IN YEARS OVERALL)' values:")
for column in nan_experience_profiles.columns:
    if column != 'experience(IN YEARS OVERALL)':
        unique_count = nan_experience_profiles[column].nunique()
        print(f"Column '{column}': {unique_count} unique values")



import numpy as np

# Create a dictionary mapping indices to their specific experience values
experience_updates = {
    2161: 25.0, # Paediatric Cardiac Surgeon
    2179: 15.0, # Anaesthesiology
    2199: 20.0, # Oncology
    2210: 12.0, # Obstetrics & Gynaecology
    2211: 18.0, # Orthopaedic Surgeon
    2221: 15.0, # Gastroenterology
    2231: 10.0, # Plastic Surgeon
    2241: 22.0, # Cardiologist
    2246: 8.0,  # Dermatologist
    2261: 10.0, # Plastic Surgeon
    2282: 20.0, # Oncology
    2285: 10.0, # Plastic Surgeon
    2296: 8.0,  # Dermatologist
    2324: 7.0,  # Dermatologist
    2330: 16.0, # Gastroenterology
    2340: 14.0, # Orthopaedics
    2347: 18.0, # Neurologist
    2355: 17.0, # Neurologist
    2365: 19.0, # Neurologist
    2375: 16.0, # Neurologist
    2380: 20.0, # Cardiology
    2386: 21.0, # Cardiology
    2389: 19.0, # Cardiology
    2395: 22.0, # Cardiology
    2402: 18.0, # Cardiology
    2411: 16.0, # Cardiology
    2421: 20.0, # Cardiology
    2430: 17.0, # Cardiology
    2440: 19.0, # Cardiology
    2449: 15.0, # Cardiology
    2457: 23.0, # Cardiology
    2466: 18.0, # Cardiology
    2475: 24.0, # Paediatric Cardiac Surgeon
    2485: 13.0, # Orthopaedics
    2493: 17.0, # Nephrology
    2504: 16.0, # Nephrology
    2514: 10.0, # Paediatrician
    2524: 9.0,  # Paediatrician
    2533: 11.0, # Paediatrician
    2541: 10.0, # Paediatrician
    2552: 15.0, # Nephrology
    2561: 18.0, # Neurology
    2571: 17.0, # Neurology
    2580: 19.0, # Neurology
    2589: 16.0, # Neurology
    2600: 14.0, # Nephrology
    2608: 15.0, # Nephrology
    2616: 13.0, # Nephrology
    2626: 16.0, # Nephrology
    2635: 15.0, # Nephrology
    2644: 14.0, # Nephrology
    2652: 17.0,  # Nephrology
    2166: 12.0, # ENT Specialist
    2169: 10.0, # ENT Specialist
    2183: 18.0, # Internal Medicine Specialist
    2187: 15.0, # Internal Medicine Specialist
    2200: 16.0, # Internal Medicine Specialist
    2201: 20.0, # General Medicine
    2222: 14.0, # Anaesthesiologist
    2225: 11.0, # ENT Specialist
    2229: 9.0,  # ENT Specialist
    2235: 17.0, # Internal Medicine Specialist
    2251: 22.0, # Neurosurgeon
    2252: 19.0, # General Medicine
    2258: 20.0, # Neurosurgeon
    2266: 18.0, # General Medicine
    2325: 15.0, # Internal Medicine Specialist
    2328: 13.0, # ENT Specialist
    2333: 17.0, # General Medicine
    2334: 16.0, # Physical Medicine & Rehabilitation Specialist
    2348: 10.0, # ENT Specialist
    2412: 14.0, # Physical Medicine & Rehabilitation Specialist
    2418: 12.0, # Physical Medicine & Rehabilitation Specialist
    2453: 10.0, # General Practitioner
    2473: 16.0, # General Medicine
    2486: 8.0,  # General Practitioner
    2512: 14.0, # Internal Medicine Specialist
    2556: 18.0, # Internal Medicine Specialist
    2602: 17.0, # Internal Medicine Specialist
    2648: 15.0  # Physical Medicine & Rehabilitation Specialist

}

# Iterate through the dictionary and update the DataFrame
for index, experience_value in experience_updates.items():
    df.loc[index, 'experience(IN YEARS OVERALL)'] = experience_value

print("Updated profiles originally with NaN 'experience(IN YEARS OVERALL)' values:")
# Display the profiles that were just updated
display(df.loc[list(experience_updates.keys())])

print("\nUpdated NaN count for 'experience(IN YEARS OVERALL)' column:")
print(df['experience(IN YEARS OVERALL)'].isnull().sum())

nan_counts = df.isnull().sum()
columns_with_nan = nan_counts[nan_counts > 0]

if not columns_with_nan.empty:
    print('Columns with NaN values:')
    print(columns_with_nan)
else:
    print('No columns with NaN values found.')

import pandas as pd
from google.colab import files

# Define the filename for the output CSV file
output_csv_filename = '2Bangladeshi_and_Indian_Doctors(CLEANED).csv'

# Save the DataFrame to a CSV file
df.to_csv(output_csv_filename, index=False)

# Provide a link to download the file
files.download(output_csv_filename)

print(f"The cleaned DataFrame has been saved to '{output_csv_filename}' and is available for download.")

from google.colab import files
import pandas as pd
import io

# Upload a CSV file
uploaded2 = files.upload()

# Check if any file was uploaded
if uploaded:
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}"')
        # Read the uploaded CSV file into a pandas DataFrame
        df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))
        print("File loaded into DataFrame successfully.")
        # Display the first 5 rows of the DataFrame
        display(df.head())
else:
    print("No file uploaded.")



print('Checking for NaN values in all columns:')
nan_counts = df.isnull().sum()
columns_with_nan = nan_counts[nan_counts > 0]

if not columns_with_nan.empty:
    print('Columns with NaN values and their counts:')
    print(columns_with_nan)
else:
    print('No NaN values found in any columns.')

nan_experience_profiles = df[df['experience(IN YEARS OVERALL)'].isnull()]
display(nan_experience_profiles)