# -*- coding: utf-8 -*-
"""5_final_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oez0FNKeGa2a_ag9kpH_vTLFx5dn9ZG4
"""

import pandas as pd
from google.colab import files

# 📌 Block 2: Upload a CSV file
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
print("✔ File Loaded Successfully:", filename)

df.head()

# 📌 Block: Summary of Every Column (Total Count, Unique Count, NaN Count)

print("📊 COLUMN SUMMARY (ALL COLUMNS)\n")

for col in df.columns:
    total_count = len(df[col])
    unique_count = df[col].nunique(dropna=True)
    nan_count = df[col].isna().sum()

    print("======================================")
    print(f"🔸 COLUMN: {col}")
    print("======================================")
    print(f"📌 Total Values: {total_count}")
    print(f"📌 Unique Values: {unique_count}")
    print(f"📌 NaN / Missing Values: {nan_count}")
    print("\n")