# -*- coding: utf-8 -*-
"""5final revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouXYARGEcVrsW1BaDx6x3qQPlX8guhqX
"""



# 📌 Block 2: Upload a CSV file
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
print("✔ File Loaded Successfully:", filename)

df.head()

# 📌 Block 3: Show unique values, count, and NaN count for each column

columns_to_show = [
    "name",
    "qualifications",
    "specialty",
    "experience(IN YEARS OVERALL)",
    "hospital",
    "location",
    "country"
]

print("\n🔍 COLUMN-WISE DETAILS (UNIQUE VALUES • COUNT • NaN COUNT):\n")

for col in columns_to_show:
    if col in df.columns:
        print(f"==============================================")
        print(f"🔸 COLUMN: {col}")
        print("==============================================")

        # Unique values
        unique_vals = df[col].unique()
        print(f"🟦 Unique Values:")
        print(unique_vals)

        # Count of unique values
        print(f"\n🟩 Count of Unique Values: {df[col].nunique()}")

        # Count of NaN values
        print(f"🟥 NaN / Missing Values: {df[col].isna().sum()}")

        print("\n")
    else:
        print(f"⚠ Column not found in file: {col}\n")

# 📌 Block: Summary of Every Column (Total Count, Unique Count, NaN Count)

print("📊 COLUMN SUMMARY (ALL COLUMNS)\n")

for col in df.columns:
    total_count = len(df[col])
    unique_count = df[col].nunique(dropna=True)
    nan_count = df[col].isna().sum()

    print("======================================")
    print(f"🔸 COLUMN: {col}")
    print("======================================")
    print(f"📌 Total Values: {total_count}")
    print(f"📌 Unique Values: {unique_count}")
    print(f"📌 NaN / Missing Values: {nan_count}")
    print("\n")

missing_experience_urls = df[df['experience(IN YEARS OVERALL)'].isnull()]['profile_url']
print("Profile URLs for rows with missing 'experience(IN YEARS OVERALL)' values:")
if not missing_experience_urls.empty:
    display(missing_experience_urls)
else:
    print("No profile URLs found for rows with missing 'experience(IN YEARS OVERALL)' values.")

experience_updates_str = """
https://sasthyaseba.com/doctors/dr-nilay-biswas : 27
https://sasthyaseba.com/doctors/dr-mohit-kharbanda : 34
https://sasthyaseba.com/doctors/dr-shouvik-ghosh : 10
https://sasthyaseba.com/doctors/dr-b-rajyalakshmi : 15
https://sasthyaseba.com/doctors/dr-u-azad-chandrasekhar : 13
https://sasthyaseba.com/doctors/dr-ashis-kumar-saha : 29
https://sasthyaseba.com/doctors/dr-dhritabrata-das : 32
https://sasthyaseba.com/doctors/dr-nandita-ghosh-dastider : 15
https://sasthyaseba.com/doctors/dr-aparupa-ghosh : 15
https://sasthyaseba.com/doctors/dr-supratip-kundu : 15
https://sasthyaseba.com/doctors/dr-karthik-munagala : 13
https://sasthyaseba.com/doctors/dr-mangadevi-c-h : 21
https://sasthyaseba.com/doctors/dr-niladri-bose : 15
https://sasthyaseba.com/doctors/dr-prakash-das : 13
https://sasthyaseba.com/doctors/asha-nayak : 27
https://sasthyaseba.com/doctors/dr-k-r-vasudevan : 17
https://sasthyaseba.com/doctors/dr-devanu-ghosh-roy : 27
https://sasthyaseba.com/doctors/dr-pragati-singhal : 13
https://sasthyaseba.com/doctors/dr-pratijyoti-ghosh : 12
https://sasthyaseba.com/doctors/dr-amitava-dasgupta : 24
https://sasthyaseba.com/doctors/dr-maharshi-nandy : 29
https://sasthyaseba.com/doctors/dr-somak-das : 23
https://sasthyaseba.com/doctors/dr-aditya-verma : 13
https://sasthyaseba.com/doctors/dr-a-aruna : 38
https://sasthyaseba.com/doctors/dr-suman-halder : 19
https://sasthyaseba.com/doctors/dr-janki-kotiya : 7
https://sasthyaseba.com/doctors/dr-ramasubramaniam : 10
https://sasthyaseba.com/doctors/dr-nilanjan-mitra : 20
https://sasthyaseba.com/doctors/dr-ayan-mukhopadhyay : 18
https://sasthyaseba.com/doctors/dr-partha-sarathi-nandi : 24
https://sasthyaseba.com/doctors/dr-biplab-dolui : 21
https://sasthyaseba.com/doctors/dr-pranab-kumar-basak : 24
https://sasthyaseba.com/doctors/dr-soham-banik : 14
https://sasthyaseba.com/doctors/dr-suvendu-maji : 15
https://sasthyaseba.com/doctors/dr-ashraful-haque : 12
https://sasthyaseba.com/doctors/dr-abhijit-chatterjee : 34
https://sasthyaseba.com/doctors/dr-reenu-jain : 19
https://sasthyaseba.com/doctors/dr-subhasish-chakraborty : 17
https://sasthyaseba.com/doctors/dr-josh : 12
https://sasthyaseba.com/doctors/dr-a-k-pathak : 8
https://sasthyaseba.com/doctors/dr-karan-malhotra : 7
https://sasthyaseba.com/doctors/dr-sibaji-phaujdar : 18
https://sasthyaseba.com/doctors/dr-saikat-sau : 14
https://sasthyaseba.com/doctors/dr-amitabh-sur : 16
https://sasthyaseba.com/doctors/dr-l-rama-devi-pasumarthy : 12
https://sasthyaseba.com/doctors/dr-indrani-syam : 10
https://sasthyaseba.com/doctors/dr-amitava-dutta : 12
https://sasthyaseba.com/doctors/dr-dibyendu-ghosh : 16
https://sasthyaseba.com/doctors/dr-subhra-das : 35
https://sasthyaseba.com/doctors/dr-tirtha-pratim-purkait : 20
https://sasthyaseba.com/doctors/dr-sreya-mallik : 19
https://sasthyaseba.com/doctors/dr-papiya-khawash : 27
https://sasthyaseba.com/doctors/dr-mainak-chatterjee : 12
https://sasthyaseba.com/doctors/dr-samujjwal-das : 10
https://sasthyaseba.com/doctors/dr-sumana-kundagrami : 20
https://sasthyaseba.com/doctors/prof-dr-subrata-bag : 17
https://sasthyaseba.com/doctors/dr-abdul-naim-ostagar : 15
https://sasthyaseba.com/doctors/dr-debajyoti-mitra : 19
https://sasthyaseba.com/doctors/dr-rituparna-chaturvedi : 18
https://sasthyaseba.com/doctors/dr-ishani-chatterjee : 13
https://sasthyaseba.com/doctors/dr-souvik-saha : 15
https://sasthyaseba.com/doctors/dr-nagaraj-s : 22
https://sasthyaseba.com/doctors/dr-jasmin-reza-susarla : 22
https://sasthyaseba.com/doctors/dr-dhananjoy-bera : 15
https://sasthyaseba.com/doctors/dr-asifa-khalid : 16
https://sasthyaseba.com/doctors/dr-biswajyoti-guha : 30
https://sasthyaseba.com/doctors/dr-anup-shyamal : 23
https://sasthyaseba.com/doctors/dr-faisal-danish : 25
https://sasthyaseba.com/doctors/dr-imran-khan : 12
https://sasthyaseba.com/doctors/dr-debasish-bhattacharyya : 22
https://sasthyaseba.com/doctors/dr-camelia-porey : 8
https://sasthyaseba.com/doctors/dr-nagaraja : 28
https://sasthyaseba.com/doctors/dr-rimi-roy-chowdhury : 17
https://sasthyaseba.com/doctors/dr-s-shakunthala : 24
https://sasthyaseba.com/doctors/dr-deepthi-raidu : 15
https://sasthyaseba.com/doctors/dr-shiva-prasad-ganji : 9
https://sasthyaseba.com/doctors/dr-monalisa-dutta : 15
https://sasthyaseba.com/doctors/dr-sujit-kar-purkayastha : 19
https://sasthyaseba.com/doctors/dr-kunal-sengupta : 34
https://sasthyaseba.com/doctors/dr-bijoy-roy-choudhury : 15
https://sasthyaseba.com/doctors/dr-kundan-chaurasia : 14
https://sasthyaseba.com/doctors/dr-priyadarshan-konar : 19
https://sasthyaseba.com/doctors/dr-ankur-dasgupta : 11
https://sasthyaseba.com/doctors/prof-dr-dk-majumdar : 33
https://sasthyaseba.com/doctors/dr-aravind-c : 30
https://sasthyaseba.com/doctors/dr-s-a-swathi : 13
https://sasthyaseba.com/doctors/dr-shouvanik-satpathy : 18
https://sasthyaseba.com/doctors/dr-srinivas-deshmukh : 21
https://sasthyaseba.com/doctors/dr-shahab-faria-shahabuddin : 10
https://sasthyaseba.com/doctors/dr-malabika-misra : 30
https://sasthyaseba.com/doctors/dr-pb-akilasree : 12
https://sasthyaseba.com/doctors/dr-kishore-subbaiah : 23
https://sasthyaseba.com/doctors/dr-praney-gupta : 14
https://sasthyaseba.com/doctors/dr-pinak-panikar : 15
https://sasthyaseba.com/doctors/dr-abhishek-mukherji : 19
https://sasthyaseba.com/doctors/prof-dr-udas-chandra-ghosh : 18
https://sasthyaseba.com/doctors/dr-sukanya-banerjee : 12
https://sasthyaseba.com/doctors/dr-bikram-haldar : 12
https://sasthyaseba.com/doctors/dr-jamenjoy-mondal : 15
https://sasthyaseba.com/doctors/dr-mohammed-saad-uddin-azmi : 14
https://sasthyaseba.com/doctors/dr-dipa-saha : 10
https://sasthyaseba.com/doctors/dr-tanmay-mukherjee : 15
https://sasthyaseba.com/doctors/dr-sourav-datta : 12
https://sasthyaseba.com/doctors/dr-partha-chatterjee : 11
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-ashish-goel : 25
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : 17
https://sasthyaseba.com/doctors/dr-supriyo-dey-sarkar : 10
https://sasthyaseba.com/doctors/dr-debjani-majumdar : 23
https://sasthyaseba.com/doctors/dr-sushma-krishna : 10
https://sasthyaseba.com/doctors/dr-amit-mandal : 17
https://sasthyaseba.com/doctors/dr-asim-kumar-pal : 33
https://sasthyaseba.com/doctors/dr-roopa-gv : 16
https://sasthyaseba.com/doctors/dr-arpan-jana : 10
https://sasthyaseba.com/doctors/dr-tripti-sharma : 15
https://sasthyaseba.com/doctors/dr-partha-sarathi-mondal : 12
https://sasthyaseba.com/doctors/dr-uma-p-trasi : 25
https://sasthyaseba.com/doctors/dr-abhijit-roy : 20
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : 17
https://sasthyaseba.com/doctors/dr-sabyasachi-bhattacharya : 17
https://sasthyaseba.com/doctors/dr-shubhranshu-shekhar-sarkar : 18
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : 40
https://sasthyaseba.com/doctors/dr-amrita-paul : 10
https://sasthyaseba.com/doctors/dr-samrat-ganguly : 5
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-rajib-bhattacharjee : 20
https://sasthyaseba.com/doctors/dr-ashok-bandyopadhyay : 10
https://sasthyaseba.com/doctors/dr-kushankur-guha : 15
https://sasthyaseba.com/doctors/dr-rajiv-dhall : 23
https://sasthyaseba.com/doctors/dr-nk-ravi : 14
https://sasthyaseba.com/doctors/dr-kalyan-kumar-gangopadhyay : 22
https://sasthyaseba.com/doctors/dr-anindya-dutt : (not found)
https://sasthyaseba.com/doctors/dr-debasish-chatterjee : 18
https://sasthyaseba.com/doctors/dr-arun-l-naik : 23
https://sasthyaseba.com/doctors/dr-pramod-saini : 17
https://sasthyaseba.com/doctors/dr-naresh-kumar-g : 13
https://sasthyaseba.com/doctors/dr-gaurav-rathore : 20
https://sasthyaseba.com/doctors/dr-kazi-s-manir : 20
https://sasthyaseba.com/doctors/dr-subhajit-pal : 10
https://sasthyaseba.com/doctors/dr-mohammed-abubakar : 33
https://sasthyaseba.com/doctors/dr-reenu-jain : 19
https://sasthyaseba.com/doctors/dr-subhasish-chakraborty : 17
https://sasthyaseba.com/doctors/dr-josh : 12
https://sasthyaseba.com/doctors/dr-a-k-pathak : 8
https://sasthyaseba.com/doctors/dr-karan-malhotra : 7
https://sasthyaseba.com/doctors/dr-sibaji-phaujdar : 18
https://sasthyaseba.com/doctors/dr-saikat-sau : 14
https://sasthyaseba.com/doctors/dr-amitabh-sur : 16
https://sasthyaseba.com/doctors/dr-l-rama-devi-pasumarthy : 12
https://sasthyaseba.com/doctors/dr-indrani-syam : 10
https://sasthyaseba.com/doctors/dr-amitava-dutta : 12
https://sasthyaseba.com/doctors/dr-dibyendu-ghosh : 16
https://sasthyaseba.com/doctors/dr-subhra-das : 35
https://sasthyaseba.com/doctors/dr-tirtha-pratim-purkait : 20
https://sasthyaseba.com/doctors/dr-sreya-mallik : 19
https://sasthyaseba.com/doctors/dr-papiya-khawash : 27
https://sasthyaseba.com/doctors/dr-mainak-chatterjee : 12
https://sasthyaseba.com/doctors/dr-samujjwal-das : 10
https://sasthyaseba.com/doctors/dr-sumana-kundagrami : 20
https://sasthyaseba.com/doctors/dr-subhasish-guha : (not found)
https://sasthyaseba.com/doctors/prof-dr-subrata-bag : 17
https://sasthyaseba.com/doctors/dr-abdul-naim-ostagar : 15
https://sasthyaseba.com/doctors/dr-debajyoti-mitra : 19
https://sasthyaseba.com/doctors/dr-rituparna-chaturvedi : 18
https://sasthyaseba.com/doctors/dr-ishani-chatterjee : 13
https://sasthyaseba.com/doctors/dr-souvik-saha : 15
https://sasthyaseba.com/doctors/dr-nagaraj-s : 22
https://sasthyaseba.com/doctors/dr-jasmin-reza-susarla : 22
https://sasthyaseba.com/doctors/dr-dhananjoy-bera : 15
https://sasthyaseba.com/doctors/dr-asifa-khalid : 16
https://sasthyaseba.com/doctors/dr-biswajyoti-guha : 30
https://sasthyaseba.com/doctors/dr-anup-shyamal : 23
https://sasthyaseba.com/doctors/dr-faisal-danish : 25
https://sasthyaseba.com/doctors/dr-imran-khan : 12
https://sasthyaseba.com/doctors/dr-debasish-bhattacharyya : 22
https://sasthyaseba.com/doctors/dr-camelia-porey : 8
https://sasthyaseba.com/doctors/dr-nagaraja : 28
https://sasthyaseba.com/doctors/dr-rimi-roy-chowdhury : 17
https://sasthyaseba.com/doctors/dr-s-shakunthala : 24
https://sasthyaseba.com/doctors/dr-deepthi-raidu : 15
https://sasthyaseba.com/doctors/dr-shiva-prasad-ganji : 9
https://sasthyaseba.com/doctors/dr-monalisa-dutta : 15
https://sasthyaseba.com/doctors/dr-mayank-baid : (not found)
https://sasthyaseba.com/doctors/dr-sujit-kar-purkayastha : 19
https://sasthyaseba.com/doctors/dr-kunal-sengupta : 34
https://sasthyaseba.com/doctors/dr-bijoy-roy-choudhury : 15
https://sasthyaseba.com/doctors/dr-kundan-chaurasia : 14
https://sasthyaseba.com/doctors/dr-isha-juneja-bharadwaj : (not found)
https://sasthyaseba.com/doctors/dr-priyadarshan-konar : 19
https://sasthyaseba.com/doctors/dr-ankur-dasgupta : 11
https://sasthyaseba.com/doctors/prof-dr-dk-majumdar : 33
https://sasthyaseba.com/doctors/dr-aravind-c : 30
https://sasthyaseba.com/doctors/dr-s-a-swathi : 13
https://sasthyaseba.com/doctors/dr-shouvanik-satpathy : 18
https://sasthyaseba.com/doctors/dr-srinivas-deshmukh : 21
https://sasthyaseba.com/doctors/dr-sudpita-sengupta : (not found)
https://sasthyaseba.com/doctors/dr-shahab-faria-shahabuddin : 10
https://sasthyaseba.com/doctors/dr-malabika-misra : 30
https://sasthyaseba.com/doctors/dr-pb-akilasree : 12
https://sasthyaseba.com/doctors/dr-kishore-subbaiah : 23
https://sasthyaseba.com/doctors/dr-praney-gupta : 14
https://sasthyaseba.com/doctors/dr-pinak-panikar : 15
https://sasthyaseba.com/doctors/dr-lalit-agarwal : (not found)
https://sasthyaseba.com/doctors/dr-abhishek-mukherji : 19
https://sasthyaseba.com/doctors/prof-dr-udas-chandra-ghosh : 18
https://sasthyaseba.com/doctors/dr-sukanya-banerjee : 12
https://sasthyaseba.com/doctors/dr-bikram-haldar : 12
https://sasthyaseba.com/doctors/dr-afzal-hussain : (not found)
https://sasthyaseba.com/doctors/dr-jamenjoy-mondal : 15
https://sasthyaseba.com/doctors/dr-mohammed-saad-uddin-azmi : 14
https://sasthyaseba.com/doctors/dr-dipa-saha : 10
https://sasthyaseba.com/doctors/dr-tanmay-mukherjee : 15
https://sasthyaseba.com/doctors/dr-sourav-datta : 12
https://sasthyaseba.com/doctors/dr-partha-chatterjee : 11
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-tripti-sharma : 15
https://sasthyaseba.com/doctors/dr-partha-sarathi-mondal : 12
https://sasthyaseba.com/doctors/dr-uma-p-trasi : 25
https://sasthyaseba.com/doctors/dr-abhijit-roy : 20
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : 17
https://sasthyaseba.com/doctors/dr-arnab-bera : (not found)
https://sasthyaseba.com/doctors/dr-sabyasachi-bhattacharya : 17
https://sasthyaseba.com/doctors/dr-shubhranshu-shekhar-sarkar : 18
https://sasthyaseba.com/doctors/dr-suryaprakash-sharma : (not found)
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : 40
https://sasthyaseba.com/doctors/dr-amrita-paul : 10
https://sasthyaseba.com/doctors/dr-samrat-ganguly : 5
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-tripti-sharma : 15
https://sasthyaseba.com/doctors/dr-partha-sarathi-mondal : 12
https://sasthyaseba.com/doctors/dr-uma-p-trasi : 25
https://sasthyaseba.com/doctors/dr-abhijit-roy : 20
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : 17
https://sasthyaseba.com/doctors/dr-arnab-bera : (not found)
https://sasthyaseba.com/doctors/dr-sabyasachi-bhattacharya : 17
https://sasthyaseba.com/doctors/dr-shubhranshu-shekhar-sarkar : 18
https://sasthyaseba.com/doctors/dr-suryaprakash-sharma : (not found)
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : 40
https://sasthyaseba.com/doctors/dr-amrita-paul : 10
https://sasthyaseba.com/doctors/dr-samrat-ganguly : 5
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-mohammed-saad-uddin-azmi : 14
https://sasthyaseba.com/doctors/dr-dipa-saha : 10
https://sasthyaseba.com/doctors/dr-tanmay-mukherjee : 15
https://sasthyaseba.com/doctors/dr-sourav-datta : 12
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-ashish-goel : 25
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : 17
https://sasthyaseba.com/doctors/dr-supriyo-dey-sarkar : 10
https://sasthyaseba.com/doctors/dr-debjani-majumdar : 23
https://sasthyaseba.com/doctors/dr-sushma-krishna : 10
https://sasthyaseba.com/doctors/dr-utsa-basu-464 : (not found)
https://sasthyaseba.com/doctors/dr-amit-mandal : 17
https://sasthyaseba.com/doctors/dr-pranita-vanjare : (not found)
https://sasthyaseba.com/doctors/dr-asim-kumar-pal : 33
https://sasthyaseba.com/doctors/dr-roopa-gv : 16
https://sasthyaseba.com/doctors/dr-arpan-jana : 10
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-ashish-goel : 25
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : 17
https://sasthyaseba.com/doctors/dr-supriyo-dey-sarkar : 10
https://sasthyaseba.com/doctors/dr-debjani-majumdar : 23
https://sasthyaseba.com/doctors/dr-sushma-krishna : 10
https://sasthyaseba.com/doctors/dr-utsa-basu-464 : (not found)
https://sasthyaseba.com/doctors/dr-amit-mandal : 17
https://sasthyaseba.com/doctors/dr-pranita-vanjare : (not found)
https://sasthyaseba.com/doctors/dr-asim-kumar-pal : 33
https://sasthyaseba.com/doctors/dr-roopa-gv : 16
https://sasthyaseba.com/doctors/dr-arpan-jana : 10
https://sasthyaseba.com/doctors/dr-tripti-sharma : 15
https://sasthyaseba.com/doctors/dr-partha-sarathi-mondal : 12
https://sasthyaseba.com/doctors/dr-uma-p-trasi : 25
https://sasthyaseba.com/doctors/dr-abhijit-roy : 20
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : 17
https://sasthyaseba.com/doctors/dr-arnab-bera : (not found)
https://sasthyaseba.com/doctors/dr-sabyasachi-bhattacharya : 17
https://sasthyaseba.com/doctors/dr-shubhranshu-shekhar-sarkar : 18
https://sasthyaseba.com/doctors/dr-suryaprakash-sharma : (not found)
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : 40
https://sasthyaseba.com/doctors/dr-amrita-paul : 10
https://sasthyaseba.com/doctors/dr-samrat-ganguly : 5
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-rajib-bhattacharjee : 20
https://sasthyaseba.com/doctors/dr-ashok-bandyopadhyay : 10
https://sasthyaseba.com/doctors/dr-kushankur-guha : 15
https://sasthyaseba.com/doctors/dr-rajiv-dhall : 23
https://sasthyaseba.com/doctors/dr-nk-ravi : 14
https://sasthyaseba.com/doctors/dr-kalyan-kumar-gangopadhyay : 22
https://sasthyaseba.com/doctors/dr-anindya-dutt : (not found)
https://sasthyaseba.com/doctors/dr-debasish-chatterjee : 18
https://sasthyaseba.com/doctors/dr-arun-l-naik : 23
https://sasthyaseba.com/doctors/dr-pramod-saini : 17
https://sasthyaseba.com/doctors/dr-naresh-kumar-g : 13
https://sasthyaseba.com/doctors/dr-gaurav-rathore : 20
https://sasthyaseba.com/doctors/dr-kazi-s-manir : 20
https://sasthyaseba.com/doctors/dr-subhajit-pal : 10
https://sasthyaseba.com/doctors/dr-mohammed-abubakar : 33
https://sasthyaseba.com/doctors/dr-reenu-jain : 19
https://sasthyaseba.com/doctors/dr-subhasish-chakraborty : 17
https://sasthyaseba.com/doctors/dr-josh : 12
https://sasthyaseba.com/doctors/dr-a-k-pathak : 8
https://sasthyaseba.com/doctors/dr-karan-malhotra : 7
https://sasthyaseba.com/doctors/dr-sibaji-phaujdar : 18
https://sasthyaseba.com/doctors/dr-saikat-sau : 14
https://sasthyaseba.com/doctors/dr-amitabh-sur : 16
https://sasthyaseba.com/doctors/dr-l-rama-devi-pasumarthy : 12
https://sasthyaseba.com/doctors/dr-indrani-syam : 10
https://sasthyaseba.com/doctors/dr-amitava-dutta : 12
https://sasthyaseba.com/doctors/dr-dibyendu-ghosh : 16
https://sasthyaseba.com/doctors/dr-subhra-das : 35
https://sasthyaseba.com/doctors/dr-tirtha-pratim-purkait : 20
https://sasthyaseba.com/doctors/dr-sreya-mallik : 19
https://sasthyaseba.com/doctors/dr-papiya-khawash : 27
https://sasthyaseba.com/doctors/dr-mainak-chatterjee : 12
https://sasthyaseba.com/doctors/dr-samujjwal-das : 10
https://sasthyaseba.com/doctors/dr-sumana-kundagrami : 20
https://sasthyaseba.com/doctors/dr-subhasish-guha : (not found)
https://sasthyaseba.com/doctors/prof-dr-subrata-bag : 17
https://sasthyaseba.com/doctors/dr-abdul-naim-ostagar : 15
https://sasthyaseba.com/doctors/dr-debajyoti-mitra : 19
https://sasthyaseba.com/doctors/dr-rituparna-chaturvedi : 18
https://sasthyaseba.com/doctors/dr-ishani-chatterjee : 13
https://sasthyaseba.com/doctors/dr-souvik-saha : 15
https://sasthyaseba.com/doctors/dr-nagaraj-s : 22
https://sasthyaseba.com/doctors/dr-jasmin-reza-susarla : 22
https://sasthyaseba.com/doctors/dr-dhananjoy-bera : 15
https://sasthyaseba.com/doctors/dr-asifa-khalid : 16
https://sasthyaseba.com/doctors/dr-biswajyoti-guha : 30
https://sasthyaseba.com/doctors/dr-anup-shyamal : 23
https://sasthyaseba.com/doctors/dr-faisal-danish : 25
https://sasthyaseba.com/doctors/dr-imran-khan : 12
https://sasthyaseba.com/doctors/dr-debasish-bhattacharyya : 22
https://sasthyaseba.com/doctors/dr-camelia-porey : 8
https://sasthyaseba.com/doctors/dr-nagaraja : 28
https://sasthyaseba.com/doctors/dr-rimi-roy-chowdhury : 17
https://sasthyaseba.com/doctors/dr-s-shakunthala : 24
https://sasthyaseba.com/doctors/dr-deepthi-raidu : 15
https://sasthyaseba.com/doctors/dr-shiva-prasad-ganji : 9
https://sasthyaseba.com/doctors/dr-monalisa-dutta : 15
https://sasthyaseba.com/doctors/dr-mayank-baid : (not found)
https://sasthyaseba.com/doctors/dr-sujit-kar-purkayastha : 19
https://sasthyaseba.com/doctors/dr-kunal-sengupta : 34
https://sasthyaseba.com/doctors/dr-bijoy-roy-choudhury : 15
https://sasthyaseba.com/doctors/dr-kundan-chaurasia : 14
https://sasthyaseba.com/doctors/dr-isha-juneja-bharadwaj : (not found)
https://sasthyaseba.com/doctors/dr-priyadarshan-konar : 19
https://sasthyaseba.com/doctors/dr-ankur-dasgupta : 11
https://sasthyaseba.com/doctors/prof-dr-dk-majumdar : 33
https://sasthyaseba.com/doctors/dr-aravind-c : 30
https://sasthyaseba.com/doctors/dr-s-a-swathi : 13
https://sasthyaseba.com/doctors/dr-shouvanik-satpathy : 18
https://sasthyaseba.com/doctors/dr-srinivas-deshmukh : 21
https://sasthyaseba.com/doctors/dr-sudpita-sengupta : (not found)
https://sasthyaseba.com/doctors/dr-shahab-faria-shahabuddin : 10
https://sasthyaseba.com/doctors/dr-malabika-misra : 30
https://sasthyaseba.com/doctors/dr-pb-akilasree : 12
https://sasthyaseba.com/doctors/dr-kishore-subbaiah : 23
https://sasthyaseba.com/doctors/dr-praney-gupta : 14
https://sasthyaseba.com/doctors/dr-pinak-panikar : 15
https://sasthyaseba.com/doctors/dr-lalit-agarwal : (not found)
https://sasthyaseba.com/doctors/dr-abhishek-mukherji : 19
https://sasthyaseba.com/doctors/prof-dr-udas-chandra-ghosh : 18
https://sasthyaseba.com/doctors/dr-sukanya-banerjee : 12
https://sasthyaseba.com/doctors/dr-bikram-haldar : 12
https://sasthyaseba.com/doctors/dr-afzal-hussain : (not found)
https://sasthyaseba.com/doctors/dr-jamenjoy-mondal : 15
https://sasthyaseba.com/doctors/dr-mohammed-saad-uddin-azmi : 14
https://sasthyaseba.com/doctors/dr-dipa-saha : 10
https://sasthyaseba.com/doctors/dr-tanmay-mukherjee : 15
https://sasthyaseba.com/doctors/dr-sourav-datta : 12
https://sasthyaseba.com/doctors/dr-partha-chatterjee : 11
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-swapan-kumar-paul : 24
https://sasthyaseba.com/doctors/dr-soumik-chaudhuri : 13
https://sasthyaseba.com/doctors/dr-avijit-basak : 19
https://sasthyaseba.com/doctors/dr-rupa-banerjee : 12
https://sasthyaseba.com/doctors/dr-bhabatosh-biswas : 29
https://sasthyaseba.com/doctors/dr-mounam-chattopadhyay : 7
https://sasthyaseba.com/doctors/dr-prarthana-mondal : 11
https://sasthyaseba.com/doctors/dr-prudhvi-gattu : 12
https://sasthyaseba.com/doctors/dr-keerthikar-reddy-k : 12
https://sasthyaseba.com/doctors/dr-sanjib-patra : 16
https://sasthyaseba.com/doctors/dr-paramita-trivedi : 22
https://sasthyaseba.com/doctors/dr-shashi-jindal : 22
https://sasthyaseba.com/doctors/dr-sanjib-chowdhury-5495 : 17
https://sasthyaseba.com/doctors/dr-moumita-bagchi : (not found)
https://sasthyaseba.com/doctors/dr-mainak-pal : 26
https://sasthyaseba.com/doctors/dr-rupak-ranjan-roy : 35
https://sasthyaseba.com/doctors/dr-swarnali-pal : 18
https://sasthyaseba.com/doctors/dr-kanagagiri : (not found)
https://sasthyaseba.com/doctors/dr-anjan-adak : 13
https://sasthyaseba.com/doctors/dr-swarnendu-samanta : 32
https://sasthyaseba.com/doctors/dr-abhijit-sarkar : 19
https://sasthyaseba.com/doctors/dr-malini-cherian : (not found)
https://sasthyaseba.com/doctors/dr-debabrata-maity : 12
https://sasthyaseba.com/doctors/dr-ritoban-saha-bhowmick : 10
https://sasthyaseba.com/doctors/dr-krishnendu-chandra : 18
https://sasthyaseba.com/doctors/dr-sujit-bhattacharya : 21
https://sasthyaseba.com/doctors/dr-shilpashree-m : 9
https://sasthyaseba.com/doctors/dr-k-sarat-chandra : 41
https://sasthyaseba.com/doctors/dr-y-indira-rani : 22
https://sasthyaseba.com/doctors/dr-shivam-gour : 18
https://sasthyaseba.com/doctors/dr-jagdish-pusa : 15
https://sasthyaseba.com/doctors/dr-subhendu-sarkar : 15
https://sasthyaseba.com/doctors/dr-champak-paul : 12
https://sasthyaseba.com/doctors/dr-santanu-basu : 29
https://sasthyaseba.com/doctors/dr-sumit-acharya : 34
https://sasthyaseba.com/doctors/dr-chandrani-bhattacharya : 15
https://sasthyaseba.com/doctors/dr-ashish-govil : 15
https://sasthyaseba.com/doctors/dr-avisek-dutta : 14
https://sasthyaseba.com/doctors/dr-saibal-chakraborty : 20
https://sasthyaseba.com/doctors/dr-atul-raut : 17
https://sasthyaseba.com/doctors/dr-dipanjan-halder : 12
https://sasthyaseba.com/doctors/dr-pradip-sen : 34
https://sasthyaseba.com/doctors/dr-pratiksha-khatun : 12
https://sasthyaseba.com/doctors/dr-joshna-naidu-b-m : 10
https://sasthyaseba.com/doctors/dr-pinki-agarwal : 12
https://sasthyaseba.com/doctors/dr-tushar-yashwant-sonavane : 23
https://sasthyaseba.com/doctors/dr-subhas-seth : 23
https://sasthyaseba.com/doctors/dr-sanjeev-kumar-mondal : (not found)
https://sasthyaseba.com/doctors/dr-arindam-mandal : 10
https://sasthyaseba.com/doctors/dr-abhishek-bhaumik : 14
https://sasthyaseba.com/doctors/dr-vishal-jalan : 15
https://sasthyaseba.com/doctors/dr-soumitra-kumar : 28
https://sasthyaseba.com/doctors/dr-ram-kumar-singh : 23
https://sasthyaseba.com/doctors/dr-dulal-bose : 27
https://sasthyaseba.com/doctors/dr-chandreyee-dey : (not found)
https://sasthyaseba.com/doctors/dr-koyyada-prashanth : 10
https://sasthyaseba.com/doctors/dr-swati-prasad : 19
https://sasthyaseba.com/doctors/dr-ipseet-mishra : 12
https://sasthyaseba.com/doctors/dr-sumita-saha : 23
https://sasthyaseba.com/doctors/dr-prof-satyabrata-ganguly : 36
https://sasthyaseba.com/doctors/dr-pradyot-kumar-jha : 33
https://sasthyaseba.com/doctors/dr-madhuri-nath-kahar : 12
https://sasthyaseba.com/doctors/dr-piyas-gargari : 13
https://sasthyaseba.com/doctors/dr-a-goutami-priyadarsani : 14
https://sasthyaseba.com/doctors/dr-chandramouli-bhattacharya : 24
https://sasthyaseba.com/doctors/dr-prince-james : 18
https://sasthyaseba.com/doctors/dr-kankana-rana : 12
https://sasthyaseba.com/doctors/dr-paramita-roy : 19
https://sasthyaseba.com/doctors/dr-c-p-s-chauhan : 21
https://sasthyaseba.com/doctors/dr-dipanjana-dutta : 17
https://sasthyaseba.com/doctors/dr-shyam-sunder-k-r : 26
https://sasthyaseba.com/doctors/dr-abhijit-saha : 18
https://sasthyaseba.com/doctors/dr-chandramouli-mukherjee : 17
https://sasthyaseba.com/doctors/dr-amit-bhowmik : 23
https://sasthyaseba.com/doctors/dr-abhishek-gulia : 14
https://sasthyaseba.com/doctors/dr-partha-pratim-bose : 37
https://sasthyaseba.com/doctors/dr-somnath-de : 25
https://sasthyaseba.com/doctors/dr-abhik-pyne : 15
https://sasthyaseba.com/doctors/dr-m-s-prasad : 19
https://sasthyaseba.com/doctors/dr-sankarsan-choudhury : 13
https://sasthyaseba.com/doctors/dr-priyanka-h-k : 10
https://sasthyaseba.com/doctors/dr-saubhik-sural : 24
https://sasthyaseba.com/doctors/dr-anirban-basu-5367 : 19
https://sasthyaseba.com/doctors/dr-sanjay-gupta : 36
https://sasthyaseba.com/doctors/dr-shibnath-mondal : 33
https://sasthyaseba.com/doctors/dr-vignesh-rajendra : 31
https://sasthyaseba.com/doctors/dr-rajarshi-goswami : (not found)
https://sasthyaseba.com/doctors/dr-sudha-s : 22
https://sasthyaseba.com/doctors/dr-fara-sahabuddin : (not found)
https://sasthyaseba.com/doctors/dr-saugat-das-gupta : 10
https://sasthyaseba.com/doctors/dr-rajesh-kapoor : 40
https://sasthyaseba.com/doctors/dr-jayanta-kumar-basu : 27
https://sasthyaseba.com/doctors/dr-soumya-kanti-bhattacharjee : 23
https://sasthyaseba.com/doctors/dr-swaroop-revannasiddaiah : 10
https://sasthyaseba.com/doctors/dr-sathish-pogula : 15
https://sasthyaseba.com/doctors/dr-amit-ray : 18
https://sasthyaseba.com/doctors/dr-pranab-biswas : 19
https://sasthyaseba.com/doctors/dr-jyoti-ranjan-mohapatra : 33
https://sasthyaseba.com/doctors/dr-swarna-latha-j : 12
https://sasthyaseba.com/doctors/dr-sanjib-mondal : 20
https://sasthyaseba.com/doctors/dr-jasmin-reza-susarla : 22
https://sasthyaseba.com/doctors/dr-dhananjoy-bera : 15
https://sasthyaseba.com/doctors/dr-asifa-khalid : 16
https://sasthyaseba.com/doctors/dr-biswajyoti-guha : 30
https://sasthyaseba.com/doctors/dr-anup-shyamal : 23
https://sasthyaseba.com/doctors/dr-faisal-danish : 25
https://sasthyaseba.com/doctors/dr-imran-khan : 12
https://sasthyaseba.com/doctors/dr-debasish-bhattacharyya : 22
https://sasthyaseba.com/doctors/dr-camelia-porey : 8
https://sasthyaseba.com/doctors/dr-nagaraja : 28
https://sasthyaseba.com/doctors/dr-rimi-roy-chowdhury : 17
https://sasthyaseba.com/doctors/dr-s-shakunthala : 24
https://sasthyaseba.com/doctors/dr-deepthi-raidu : 15
https://sasthyaseba.com/doctors/dr-shiva-prasad-ganji : 9
https://sasthyaseba.com/doctors/dr-monalisa-dutta : 15
https://sasthyaseba.com/doctors/dr-mayank-baid : (not found)
https://sasthyaseba.com/doctors/dr-sujit-kar-purkayastha : 19
https://sasthyaseba.com/doctors/dr-kunal-sengupta : 34
https://sasthyaseba.com/doctors/dr-bijoy-roy-choudhury : 15
https://sasthyaseba.com/doctors/dr-kundan-chaurasia : 14
https://sasthyaseba.com/doctors/dr-isha-juneja-bharadwaj : (not found)
https://sasthyaseba.com/doctors/dr-priyadarshan-konar : 19
https://sasthyaseba.com/doctors/dr-ankur-dasgupta : 11
https://sasthyaseba.com/doctors/prof-dr-dk-majumdar : 33
https://sasthyaseba.com/doctors/dr-aravind-c : 30
https://sasthyaseba.com/doctors/dr-s-a-swathi : 13
https://sasthyaseba.com/doctors/dr-shouvanik-satpathy : 18
https://sasthyaseba.com/doctors/dr-srinivas-deshmukh : 21
https://sasthyaseba.com/doctors/dr-sudpita-sengupta : (not found)
https://sasthyaseba.com/doctors/dr-shahab-faria-shahabuddin : 10
https://sasthyaseba.com/doctors/dr-malabika-misra : 30
https://sasthyaseba.com/doctors/dr-pb-akilasree : 12
https://sasthyaseba.com/doctors/dr-kishore-subbaiah : 23
https://sasthyaseba.com/doctors/dr-praney-gupta : 14
https://sasthyaseba.com/doctors/dr-pinak-panikar : 15
https://sasthyaseba.com/doctors/dr-lalit-agarwal : (not found)
https://sasthyaseba.com/doctors/dr-abhishek-mukherji : 19
https://sasthyaseba.com/doctors/prof-dr-udas-chandra-ghosh : 18
https://sasthyaseba.com/doctors/dr-sukanya-banerjee : 12
https://sasthyaseba.com/doctors/dr-bikram-haldar : 12
https://sasthyaseba.com/doctors/dr-afzal-hussain : (not found)
https://sasthyaseba.com/doctors/dr-jamenjoy-mondal : 15
https://sasthyaseba.com/doctors/dr-mohammed-saad-uddin-azmi : 14
https://sasthyaseba.com/doctors/dr-dipa-saha : 10
https://sasthyaseba.com/doctors/dr-tanmay-mukherjee : 15
https://sasthyaseba.com/doctors/dr-sourav-datta : 12
https://sasthyaseba.com/doctors/dr-partha-chatterjee : 11
https://sasthyaseba.com/doctors/dr-abhra-mondal : 4
https://sasthyaseba.com/doctors/dr-aparna-krishnappa : 6
https://sasthyaseba.com/doctors/dr-prabir-bijoy-kar : 34
https://sasthyaseba.com/doctors/dr-tapas-roy : 33
https://sasthyaseba.com/doctors/drshobha-naidu : 22
https://sasthyaseba.com/doctors/dr-syed-mahammad-azad : (not found)
https://sasthyaseba.com/doctors/dr-nikhilesh-das : 22
https://sasthyaseba.com/doctors/dr-meghdeep-mukhopadhyay : 23
https://sasthyaseba.com/doctors/dr-chandra-mohan-raju : 19
https://sasthyaseba.com/doctors/dr-ashish-goel : 25
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : 17
https://sasthyaseba.com/doctors/dr-supriyo-dey-sarkar : 10
https://sasthyaseba.com/doctors/dr-debjani-majumdar : 23
https://sasthyaseba.com/doctors/dr-sushma-krishna : 10
https://sasthyaseba.com/doctors/dr-utsa-basu-464 : (not found)
https://sasthyaseba.com/doctors/dr-amit-mandal : 17
https://sasthyaseba.com/doctors/dr-pranita-vanjare : (not found)
https://sasthyaseba.com/doctors/dr-asim-kumar-pal : 33
https://sasthyaseba.com/doctors/dr-roopa-gv : 16
https://sasthyaseba.com/doctors/dr-arpan-jana : 10
https://sasthyaseba.com/doctors/dr-tripti-sharma : 15
https://sasthyaseba.com/doctors/dr-partha-sarathi-mondal : 12
https://sasthyaseba.com/doctors/dr-uma-p-trasi : 25
https://sasthyaseba.com/doctors/dr-abhijit-roy : 20
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : 17
https://sasthyaseba.com/doctors/dr-arnab-bera : (not found)
https://sasthyaseba.com/doctors/dr-sabyasachi-bhattacharya : 17
https://sasthyaseba.com/doctors/dr-shubhranshu-shekhar-sarkar : 18
https://sasthyaseba.com/doctors/dr-suryaprakash-sharma : (not found)
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : 40
https://sasthyaseba.com/doctors/dr-amrita-paul : 10
https://sasthyaseba.com/doctors/dr-samrat-ganguly : 5
https://sasthyaseba.com/doctors/dr-pankaj-kanti-jha : 27
https://sasthyaseba.com/doctors/dr-syed-tabish-areeb-rahman : 12
https://sasthyaseba.com/doctors/dr-madhusudhan-h-r : 20
https://sasthyaseba.com/doctors/dr-nidhi-kanchan-nihal : 15
https://sasthyaseba.com/doctors/dr-monita-datta : 21
https://sasthyaseba.com/doctors/dr-santhosh-kumar-padankanti : 16
https://sasthyaseba.com/doctors/dr-rajarshi-bandyopadhyay : 31
https://sasthyaseba.com/doctors/dr-vijay-kumar-sinha : 12
https://sasthyaseba.com/doctors/dr-raghunath-c-n : 23
https://sasthyaseba.com/doctors/dr-madhuchanda-kar : 26
https://sasthyaseba.com/doctors/dr-biman-ghosh : 26
https://sasthyaseba.com/doctors/dr-poulomee-basu : 13
https://sasthyaseba.com/doctors/dr-ramana-mancherla : 14
https://sasthyaseba.com/doctors/dr-santanu-bag : 22
https://sasthyaseba.com/doctors/dr-sagi-swathi : 14
https://sasthyaseba.com/doctors/dr-poulumi-basu : 15
https://sasthyaseba.com/doctors/dr-sarbajit-das : (not found)
https://sasthyaseba.com/doctors/dr-pallav-kumar-ghoshal : 17
https://sasthyaseba.com/doctors/dr-sandip-kumar-manna : 13
https://sasthyaseba.com/doctors/dr-sandip-sardar : 11
https://sasthyaseba.com/doctors/dr-nilay-biswas : 27
https://sasthyaseba.com/doctors/dr-mohit-kharbanda : 34
https://sasthyaseba.com/doctors/dr-shouvik-ghosh : 10
https://sasthyaseba.com/doctors/dr-b-rajyalakshmi : 15
https://sasthyaseba.com/doctors/dr-u-azad-chandrasekhar : 13
https://sasthyaseba.com/doctors/dr-ashis-kumar-saha : 29
https://sasthyaseba.com/doctors/dr-dhritabrata-das : 32
https://sasthyaseba.com/doctors/dr-nandita-ghosh-dastider : 15
https://sasthyaseba.com/doctors/dr-aparupa-ghosh : 15
https://sasthyaseba.com/doctors/dr-supratip-kundu : 15
https://sasthyaseba.com/doctors/dr-karthik-munagala : 13
https://sasthyaseba.com/doctors/dr-mangadevi-c-h : 21
https://sasthyaseba.com/doctors/dr-niladri-bose : 15
https://sasthyaseba.com/doctors/dr-prakash-das : 13
https://sasthyaseba.com/doctors/asha-nayak : 27
https://sasthyaseba.com/doctors/dr-k-r-vasudevan : 17
https://sasthyaseba.com/doctors/dr-devanu-ghosh-roy : 27
https://sasthyaseba.com/doctors/dr-pragati-singhal : 13
https://sasthyaseba.com/doctors/dr-pratijyoti-ghosh : 12
https://sasthyaseba.com/doctors/dr-amitava-dasgupta : 24
https://sasthyaseba.com/doctors/dr-maharshi-nandy : 29
https://sasthyaseba.com/doctors/dr-somak-das : 23
https://sasthyaseba.com/doctors/dr-aditya-verma : 13
https://sasthyaseba.com/doctors/dr-a-aruna : 38
https://sasthyaseba.com/doctors/dr-suman-halder : 19
https://sasthyaseba.com/doctors/dr-janki-kotiya : 7
https://sasthyaseba.com/doctors/dr-ramasubramaniam : 10
https://sasthyaseba.com/doctors/dr-nilanjan-mitra : 20
https://sasthyaseba.com/doctors/dr-ayan-mukhopadhyay : 18
https://sasthyaseba.com/doctors/dr-partha-sarathi-nandi : 24
https://sasthyaseba.com/doctors/dr-biplab-dolui : 21
https://sasthyaseba.com/doctors/dr-pranab-kumar-basak : 24
https://sasthyaseba.com/doctors/dr-soham-banik : 14
https://sasthyaseba.com/doctors/dr-suvendu-maji : 15
https://sasthyaseba.com/doctors/dr-ashraful-haque : 12
https://sasthyaseba.com/doctors/dr-abhijit-chatterjee : 34
https://sasthyaseba.com/doctors/dr-srinivas-kancherla : 33
https://sasthyaseba.com/doctors/dr-shouvik-chowdhury : 12
https://sasthyaseba.com/doctors/dr-d-v-l-narayana-rao : 27
https://sasthyaseba.com/doctors/dr-naresh-dude : 14
https://sasthyaseba.com/doctors/dr-manisha-das-mondal : 26
https://sasthyaseba.com/doctors/dr-somnath-mallik : 32
https://sasthyaseba.com/doctors/dr-neelanjana-paul : 25
https://sasthyaseba.com/doctors/dr-sumitava-dev : 13
https://sasthyaseba.com/doctors/dr-debadeep-chakraborty : 17
https://sasthyaseba.com/doctors/dr-raja-basu : 22
https://sasthyaseba.com/doctors/dr-debashis-chatterjee : 34
https://sasthyaseba.com/doctors/dr-swetha-s : (not found)
https://sasthyaseba.com/doctors/dr-nitin-leekha : 15
https://sasthyaseba.com/doctors/dr-bishnupada-samanta : 8
https://sasthyaseba.com/doctors/dr-aditya-patil : 13
https://sasthyaseba.com/doctors/dr-chandan-chakraborty : 30
https://sasthyaseba.com/doctors/dr-sanjay-govil : 30
https://sasthyaseba.com/doctors/dr-sayandip-ghosh : 18
https://sasthyaseba.com/doctors/dr-fakhra-masroor : (not found)
https://sasthyaseba.com/doctors/dr-ranadip-chatterjee : 12
https://sasthyaseba.com/doctors/dr-shamik-gope : 17
https://sasthyaseba.com/doctors/dr-amit-k-devra : 15
https://sasthyaseba.com/doctors/dr-swati-sachin-jadhav : 23
https://sasthyaseba.com/doctors/dr-ray-george : (not found)
https://sasthyaseba.com/doctors/dr-mahfuz-arif : 10
https://sasthyaseba.com/doctors/dr-t-thrivikram : 22
https://sasthyaseba.com/doctors/dr-sudipto-mukherjee : 28
https://sasthyaseba.com/doctors/dr-sabyasachi-bardhan : 19
https://sasthyaseba.com/doctors/dr-amit-kumar-das : 21
https://sasthyaseba.com/doctors/dr-punit-singla : 23
https://sasthyaseba.com/doctors/dr-saubhik-das : 15
https://sasthyaseba.com/doctors/dr-somen-sunfui : 16
https://sasthyaseba.com/doctors/dr-abir-mukherjee : 23
https://sasthyaseba.com/doctors/prof-dr-siddhartha-das : 27
https://sasthyaseba.com/doctors/dr-manoj-kumar-mahata : 12
https://sasthyaseba.com/doctors/dr-sanjukta-dey : 26
https://sasthyaseba.com/doctors/dr-sujata-das : 17
https://sasthyaseba.com/doctors/dr-debashis-banerjee : 28
https://sasthyaseba.com/doctors/dr-anirban-ray : 19
https://sasthyaseba.com/doctors/dr-suman-nandi : 33
https://sasthyaseba.com/doctors/dr-pragya-kaul : 12
https://sasthyaseba.com/doctors/dr-anish-chakraborty : 10
https://sasthyaseba.com/doctors/dr-arijita-chatterjee : 8
https://sasthyaseba.com/doctors/dr-soumik-dhar : 19
https://sasthyaseba.com/doctors/dr-sabyasachi-ray : 30
https://sasthyaseba.com/doctors/dr-md-fardil-hossain-faisal : 16
https://sasthyaseba.com/doctors/dr-arghya-basu : (not found)
https://sasthyaseba.com/doctors/dr-tanuka-das : 16
https://sasthyaseba.com/doctors/dr-shyam-sunder-reddy : 16
https://sasthyaseba.com/doctors/dr-girish-rao-s : 31
https://sasthyaseba.com/doctors/dr-rangan-bhattacharya : 25
https://sasthyaseba.com/doctors/dr-anurag-lavekar : 14
https://sasthyaseba.com/doctors/dr-akhilesh-kumer-agarwal : 19
https://sasthyaseba.com/doctors/dr-shashi-vardhan-janjirala : 11
https://sasthyaseba.com/doctors/dr-rajib-bhattacharjee : 20
https://sasthyaseba.com/doctors/dr-ashok-bandyopadhyay : 10
https://sasthyaseba.com/doctors/dr-kushankur-guha : 15
https://sasthyaseba.com/doctors/dr-indrani-sen : (not found)
https://sasthyaseba.com/doctors/dr-rajiv-dhall : 23
https://sasthyaseba.com/doctors/dr-nk-ravi : 14
https://sasthyaseba.com/doctors/dr-kalyan-kumar-gangopadhyay : 22
https://sasthyaseba.com/doctors/dr-anindya-dutt : (not found)
https://sasthyaseba.com/doctors/dr-debasish-chatterjee : 18
https://sasthyaseba.com/doctors/dr-arun-l-naik : 23
https://sasthyaseba.com/doctors/dr-pramod-saini : 17

"""

# Split the string into individual lines and process each line
updates = experience_updates_str.strip().split('\n')

updated_count = 0
for entry in updates:
    if entry:
        try:
            url, experience_str = entry.split(' : ')
            experience = float(experience_str)
            # Update the DataFrame where profile_url matches
            df.loc[df['profile_url'] == url.strip(), 'experience(IN YEARS OVERALL)'] = experience
            updated_count += 1
        except ValueError as e:
            print(f"Skipping invalid entry '{entry}': {e}")

print(f"Successfully updated {updated_count} entries for 'experience(IN YEARS OVERALL)' column.")

# Verify the updates by checking NaN count again or displaying affected rows
print("\nVerifying NaN count in 'experience(IN YEARS OVERALL)' after updates:")
nan_count_after_update = df['experience(IN YEARS OVERALL)'].isnull().sum()
print(f"NaN values in 'experience(IN YEARS OVERALL)': {nan_count_after_update}")

# Optionally, display a sample of updated rows (if there are any and they were originally NaN)
# To do this reliably, we'd need to store the original NaN indices and check those.
# For now, let's just confirm the reduction in NaN count.

initial_rows = len(df)
df.dropna(subset=['experience(IN YEARS OVERALL)'], inplace=True)
final_rows = len(df)

print(f"Dropped {initial_rows - final_rows} rows with missing 'experience(IN YEARS OVERALL)' values.")
print(f"DataFrame now has {final_rows} rows.")

# Verify NaN count after dropping rows
nan_count_after_drop = df['experience(IN YEARS OVERALL)'].isnull().sum()
print(f"NaN values in 'experience(IN YEARS OVERALL)' after dropping: {nan_count_after_drop}")

display(df.head())

print("Checking for NaN values and their counts in each column:")
for column in df.columns:
    total_values = len(df[column])
    nan_count = df[column].isnull().sum()
    if nan_count > 0:
        print(f"- Column '{column}': Total values = {total_values}, NaN values = {nan_count}")
    else:
        print(f"- Column '{column}': No NaN values (Total values = {total_values})")

"""**Reasoning**:
To summarize the unique values in each column, I will iterate through all columns in the DataFrame and print the number of unique values for each.


"""

print("Unique values per column:")
for column in df.columns:
    unique_count = df[column].nunique()
    print(f"- {column}: {unique_count} unique values")

missing_qualifications_indices = df[df['specialty'].isnull()].index.tolist()
print("Indices of rows with missing 'qualifications' values:")
if missing_qualifications_indices:
    print(missing_qualifications_indices)
else:
    print("No rows with missing 'qualifications' values found.")

missing_specialty_urls = df[df['specialty'].isnull()]['profile_url']
print("Profile URLs for rows with missing 'specialty' values:")
if not missing_specialty_urls.empty:
    for url in missing_specialty_urls:
        print(url)
else:
    print("No profile URLs found for rows with missing 'specialty' values.")

specialty_updates_str = """
https://sasthyaseba.com/doctors/dr-md-aminul-islam-9748 → Cardiology
https://sasthyaseba.com/doctors/asst-prof-dr-md-serajus-saleheen → Orthopaedics
https://sasthyaseba.com/doctors/dr-ashraful-haque-chowdhury → Neurology
https://sasthyaseba.com/doctors/asst-prof-dr-sabbir-ahmed → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-s-m-atiqul-islam → Gastroenterology
https://sasthyaseba.com/doctors/asst-prof-dr-m-a-wahed → Cardiology
https://sasthyaseba.com/doctors/prof-dr-md-doulotuzzaman → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-md-rezaul-karim-8871 → Orthopaedics
https://sasthyaseba.com/doctors/dr-bijoy-sankar-parial → Cardiology
https://sasthyaseba.com/doctors/dr-md-mahmud-hasan-8724 → Medicine
https://sasthyaseba.com/doctors/dr-khaled-bin-islam → Cardiology
https://sasthyaseba.com/doctors/dr-abm-tofazzal-hossain → Medicine
https://sasthyaseba.com/doctors/prof-dr-md-shafiul-alam → Gastroenterology
https://sasthyaseba.com/doctors/dr-ahm-azgar-ali-chowdhury → Medicine
https://sasthyaseba.com/doctors/dr-sumon-talukder → Cardiology
https://sasthyaseba.com/doctors/dr-sukanta-bhattacharyya → Neurology
https://sasthyaseba.com/doctors/dr-mohammad-arifuzzaman-8632 → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-sm-mesbah-uddin-ahmed → Orthopaedics
https://sasthyaseba.com/doctors/asst-prof-dr-jabed-jahangir-tuhin → Medicine
https://sasthyaseba.com/doctors/asst-prof-dr-md-amanul-haque-bappy → Cardiology
https://sasthyaseba.com/doctors/dr-md-abirul-islam → Medicine
https://sasthyaseba.com/doctors/dr-md-asif-rabbani → Cardiology
https://sasthyaseba.com/doctors/dr-rajiv-s-r → Orthopaedics
https://sasthyaseba.com/doctors/dr-jayanthi-t-v → Gynaecology
https://sasthyaseba.com/doctors/dr-sudhindra-m-rao → Orthopaedics
https://sasthyaseba.com/doctors/dr-vignesh-jayakumar → Cardiology
https://sasthyaseba.com/doctors/dr-nithya-v → Gynaecology
https://sasthyaseba.com/doctors/dr-archana-muralidharan → Gynaecology
https://sasthyaseba.com/doctors/dr-md-aminul-islam-9748 → Cardiology
https://sasthyaseba.com/doctors/asst-prof-dr-md-serajus-saleheen → Orthopaedics
https://sasthyaseba.com/doctors/dr-ashraful-haque-chowdhury → Neurology
https://sasthyaseba.com/doctors/asst-prof-dr-sabbir-ahmed → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-s-m-atiqul-islam → Gastroenterology
https://sasthyaseba.com/doctors/asst-prof-dr-m-a-wahed → Cardiology
https://sasthyaseba.com/doctors/prof-dr-md-doulotuzzaman → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-md-rezaul-karim-8871 → Orthopaedics
https://sasthyaseba.com/doctors/dr-bijoy-sankar-parial → Cardiology
https://sasthyaseba.com/doctors/dr-md-mahmud-hasan-8724 → Medicine
https://sasthyaseba.com/doctors/dr-khaled-bin-islam → Cardiology
https://sasthyaseba.com/doctors/dr-abm-tofazzal-hossain → Medicine
https://sasthyaseba.com/doctors/prof-dr-md-shafiul-alam → Gastroenterology
https://sasthyaseba.com/doctors/dr-ahm-azgar-ali-chowdhury → Medicine
https://sasthyaseba.com/doctors/dr-sumon-talukder → Cardiology
https://sasthyaseba.com/doctors/dr-sukanta-bhattacharyya → Neurology
https://sasthyaseba.com/doctors/dr-mohammad-arifuzzaman-8632 → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-sm-mesbah-uddin-ahmed → Orthopaedics
https://sasthyaseba.com/doctors/asst-prof-dr-jabed-jahangir-tuhin → Medicine
https://sasthyaseba.com/doctors/asst-prof-dr-md-amanul-haque-bappy → Cardiology
https://sasthyaseba.com/doctors/dr-md-abirul-islam → Medicine
https://sasthyaseba.com/doctors/dr-md-asif-rabbani → Cardiology
https://sasthyaseba.com/doctors/dr-rajiv-s-r → Orthopaedics
https://sasthyaseba.com/doctors/dr-jayanthi-t-v → Gynaecology
https://sasthyaseba.com/doctors/dr-sudhindra-m-rao → Orthopaedics
https://sasthyaseba.com/doctors/dr-vignesh-jayakumar → Cardiology
https://sasthyaseba.com/doctors/dr-nithya-v → Gynaecology
https://sasthyaseba.com/doctors/dr-archana-muralidharan → Gynaecology
https://sasthyaseba.com/doctors/dr-saumik-das → Medicine
https://sasthyaseba.com/doctors/dr-bikash-chandra-mondal → Cardiology
https://sasthyaseba.com/doctors/dr-amitabha-roychoudhury → Neurology
https://sasthyaseba.com/doctors/asst-prof-dr-md-khaled-shariar → Medicine
https://sasthyaseba.com/doctors/assoc-prof-dr-quazi-shahid-ul-alam → Gastroenterology
https://sasthyaseba.com/doctors/dr-md-saiful-islam-moon → Cardiology
https://sasthyaseba.com/doctors/asst-prof-dr-abm-nizam-uddin-mojumder → Medicine
https://sasthyaseba.com/doctors/dr-mohammad-mahsin → Cardiology
https://sasthyaseba.com/doctors/asst-prof-dr-md-hasan-hafijur-rahman → Medicine
https://sasthyaseba.com/doctors/dr-nasiruddin-tamim → Cardiology
https://sasthyaseba.com/doctors/assoc-prof-dr-md-rafiqul-islam-sarkar → Orthopaedics
https://sasthyaseba.com/doctors/asst-prof-dr-ariful-rahman → Medicine
https://sasthyaseba.com/doctors/dr-mehdi-feroz-hasan-raju → Cardiology
https://sasthyaseba.com/doctors/dr-rizwan-jamil → Medicine
https://sasthyaseba.com/doctors/dr-major-s-m-iqbal-hossain → Orthopaedics
https://sasthyaseba.com/doctors/asst-prof-dr-mst-roksana-begum → Gynaecology
https://sasthyaseba.com/doctors/dr-md-siddiqur-rahman-tutul → Cardiology
https://sasthyaseba.com/doctors/dr-badrunnesa → Gynaecology
https://sasthyaseba.com/doctors/dr-md-mostafizur-rahman-6761 → Medicine
https://sasthyaseba.com/doctors/dr-md-abdus-sabur → Cardiology
https://sasthyaseba.com/doctors/prof-dr-colonel-md-mosleh-uddin → Medicine
https://sasthyaseba.com/doctors/asst-prof-dr-md-monzurul-haque → Cardiology
https://sasthyaseba.com/doctors/asst-prof-dr-afroza-suraya-majumder → Gynaecology
https://sasthyaseba.com/doctors/dr-aam-nafiz → Medicine
https://sasthyaseba.com/doctors/prof-dr-md-abdul-hannan → Cardiology
https://sasthyaseba.com/doctors/prof-dr-md-rezaul-karim-chowdhury-6475 → Gastroenterology
https://sasthyaseba.com/doctors/dr-sayan-hazra-6400 → Medicine
https://sasthyaseba.com/doctors/dr-rajat-basak → Cardiology
https://sasthyaseba.com/doctors/dr-sohail-hossain → Medicine
https://sasthyaseba.com/doctors/prof-dr-chandan-kumar-das → Gastroenterology
https://sasthyaseba.com/doctors/asst-prof-dr-dr-syed-md-tipu-sultan → Medicine
https://sasthyaseba.com/doctors/dr-ashis-kumar-saha → Cardiology
https://sasthyaseba.com/doctors/dr-sujit-kumar-saha → Medicine
https://sasthyaseba.com/doctors/dr-kaushik-das → Cardiology
https://sasthyaseba.com/doctors/dr-mangadevi-c-h → Gynaecology
https://sasthyaseba.com/doctors/dr-maya-pai-dhungat → Gynaecology
https://sasthyaseba.com/doctors/dr-sayantan-ghosh → Medicine
https://sasthyaseba.com/doctors/dr-jyoti-deb → Cardiology
https://sasthyaseba.com/doctors/dr-arpan-chaudhuri → Medicine
https://sasthyaseba.com/doctors/dr-milind-anil-naik → Orthopaedics
https://sasthyaseba.com/doctors/dr-saravanan-ankichetty → Cardiology
https://sasthyaseba.com/doctors/dr-paul-t-henry → Medicine
https://sasthyaseba.com/doctors/dr-souvik-chandra → Cardiology
https://sasthyaseba.com/doctors/dr-debadeep-chakraborty → Medicine
https://sasthyaseba.com/doctors/dr-suchir-maitra → Cardiology
https://sasthyaseba.com/doctors/dr-pradeep-narayan-sahoo → Medicine
https://sasthyaseba.com/doctors/dr-vikram-dalvi → Cardiology
https://sasthyaseba.com/doctors/dr-shamik-gope → Medicine
https://sasthyaseba.com/doctors/dr-tk-hazra → Cardiology
https://sasthyaseba.com/doctors/dr-sankar-prasad-sinha → Medicine
https://sasthyaseba.com/doctors/dr-manojendra-narayan-bhattacharyya → Cardiology
https://sasthyaseba.com/doctors/dr-chandan-chakraborty-7886 → Medicine
https://sasthyaseba.com/doctors/dr-bhaskar-mukherjee → Cardiology
https://sasthyaseba.com/doctors/dr-abir-mukherjee → Medicine
https://sasthyaseba.com/doctors/dr-anirban-ray → Cardiology
https://sasthyaseba.com/doctors/dr-anish-chakraborty → Medicine
https://sasthyaseba.com/doctors/dr-girish-rao-s → Dentistry
https://sasthyaseba.com/doctors/dr-mahadev-pokale → Cardiology
https://sasthyaseba.com/doctors/dr-pavithra-r → Gynaecology
https://sasthyaseba.com/doctors/dr-koustubh-chakraborty → Medicine
https://sasthyaseba.com/doctors/dr-surajit-swargiary → Cardiology
https://sasthyaseba.com/doctors/dr-rohan-sinha → Medicine
https://sasthyaseba.com/doctors/dr-r-manjunath → Cardiology
https://sasthyaseba.com/doctors/dr-samujjwal-das → Medicine
https://sasthyaseba.com/doctors/dr-asifa-khalid → Medicine
https://sasthyaseba.com/doctors/dr-dhritiman-mukherjee → Medicine
https://sasthyaseba.com/doctors/ms-sarmistha-sinha-saha → Psychology
https://sasthyaseba.com/doctors/dr-kausik-kumar-das → Cardiology
https://sasthyaseba.com/doctors/dr-pinak-panikar → Medicine
https://sasthyaseba.com/doctors/dr-boopesh-pugazhendi → Orthopaedics
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra → Medicine
https://sasthyaseba.com/doctors/dr-ranbir-chowdhary → Cardiology
https://sasthyaseba.com/doctors/dr-roopa-gv → Neurology
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh → Medicine
https://sasthyaseba.com/doctors/dr-kamlendu-haldar → Cardiology
https://sasthyaseba.com/doctors/dr-pradip-pai-dhungat → Gastroenterology
https://sasthyaseba.com/doctors/dr-samrat-ganguly → Medicine
https://sasthyaseba.com/doctors/dr-nidhi-kanchan-nihal → Medicine
https://sasthyaseba.com/doctors/dr-vikram-m-bhardwaj → Orthopaedics
https://sasthyaseba.com/doctors/dr-rajarshi-bandyopadhyay → Medicine
https://sasthyaseba.com/doctors/dr-pallav-kumar-ghoshal → Medicine
https://sasthyaseba.com/doctors/dr-devaki-thatte-dalvi → Gynaecology
https://sasthyaseba.com/doctors/dr-sanjib-chowdhury-5495 → Medicine
https://sasthyaseba.com/doctors/dr-ritoban-saha-bhowmick → Medicine
https://sasthyaseba.com/doctors/dr-sima-datta-ray → Gynaecology
https://sasthyaseba.com/doctors/dr-swagato-chowdhury → Medicine
https://sasthyaseba.com/doctors/dr-subhas-seth → Medicine
https://sasthyaseba.com/doctors/dr-arindam-mandal → Medicine
https://sasthyaseba.com/doctors/dr-alangkar-saha → Medicine
https://sasthyaseba.com/doctors/prof-dr-rakhi-sanyal-dutta-sarma → Gynaecology
https://sasthyaseba.com/doctors/dr-sonia-mary-kurian → Gynaecology
https://sasthyaseba.com/doctors/dr-abhik-pyne → Medicine
https://sasthyaseba.com/doctors/dr-m-s-prasad → Medicine
https://sasthyaseba.com/doctors/dr-sankarsan-choudhury → Medicine
https://sasthyaseba.com/doctors/dr-bhaskar-reddy-molluru → Orthopaedics
https://sasthyaseba.com/doctors/dr-debarghya-chatterjee → Medicine

"""

# Split the string into individual lines and process each line
updates = specialty_updates_str.strip().split('\n')

updated_count = 0
for entry in updates:
    if entry:
        try:
            url, specialty_name = entry.split(' → ', 1)
            # Update the DataFrame where profile_url matches
            df.loc[df['profile_url'] == url.strip(), 'specialty'] = specialty_name.strip()
            updated_count += 1
        except ValueError as e:
            print(f"Skipping invalid entry '{entry}': {e}")

print(f"Successfully updated {updated_count} entries for 'specialty' column.")

# Verify the updates by checking NaN count again
print("\nVerifying NaN count in 'specialty' after updates:")
nan_count_after_update = df['specialty'].isnull().sum()
print(f"NaN values in 'specialty': {nan_count_after_update}")



qualifications_updates_str = """
https://sasthyaseba.com/doctors/dr-ummy-salma-munni : MBBS, MS
https://sasthyaseba.com/doctors/smaranika-tripathy : MSc Psychology
https://sasthyaseba.com/doctors/barnali-ghosh : MA Psychology
https://sasthyaseba.com/doctors/fatema-tuz-zohra-7046 : MBBS, MD
https://sasthyaseba.com/doctors/mahfuza-afroz-shathi : MBBS, MD
https://sasthyaseba.com/doctors/dr-shamsunnahar-nahid : MBBS, MD
https://sasthyaseba.com/doctors/asha-nayak : BPT, MPT
https://sasthyaseba.com/doctors/dr-sayantan-ghosh : MBBS, MD
https://sasthyaseba.com/doctors/dr-shamik-gope : MBBS, MS
https://sasthyaseba.com/doctors/dr-sujata-das : MBBS, MD
https://sasthyaseba.com/doctors/dr-md-rabiul-islam-5224 : BDS, Diploma
https://sasthyaseba.com/doctors/dr-girish-rao-s : BDS, MDS
https://sasthyaseba.com/doctors/dr-inamuddin : BDS, MDS
https://sasthyaseba.com/doctors/dr-samujjwal-das : MBBS, MD
https://sasthyaseba.com/doctors/dr-asifa-khalid : MBBS, MD
https://sasthyaseba.com/doctors/dr-dhritiman-mukherjee : MBBS, MD
https://sasthyaseba.com/doctors/ms-sarmistha-sinha-saha : MSc Psychology
https://sasthyaseba.com/doctors/dr-mahendra-azad : BDS, MDS
https://sasthyaseba.com/doctors/dr-pinak-panikar : MBBS, MS
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : MBBS, MD
https://sasthyaseba.com/doctors/dr-uma-p-trasi : MBBS, MD
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : MBBS, MD
https://sasthyaseba.com/doctors/dr-nidhi-kanchan-nihal : MBBS, MD
https://sasthyaseba.com/doctors/dr-rajarshi-bandyopadhyay : MBBS, MS
https://sasthyaseba.com/doctors/dr-poulomee-basu : BDS, MDS
https://sasthyaseba.com/doctors/dr-pallav-kumar-ghoshal : MBBS, MD
https://sasthyaseba.com/doctors/dr-prarthana-mondal : BDS, MDS
https://sasthyaseba.com/doctors/dr-sanjib-chowdhury-5495 : MBBS, MD
https://sasthyaseba.com/doctors/ms-mariah-teresa-lobo : MSc Psychology
https://sasthyaseba.com/doctors/dr-ritoban-saha-bhowmick : MBBS, MD
https://sasthyaseba.com/doctors/dr-champak-paul : BDS, MDS
https://sasthyaseba.com/doctors/dr-swagato-chowdhury : MBBS, MD
https://sasthyaseba.com/doctors/dr-subhas-seth : MBBS, MS
https://sasthyaseba.com/doctors/dr-arindam-mandal : MBBS, MD
https://sasthyaseba.com/doctors/dr-alangkar-saha : MBBS, MD
https://sasthyaseba.com/doctors/dr-madhuri-nath-kahar : BDS, MDS
https://sasthyaseba.com/doctors/dr-abhik-pyne : MBBS, MD
https://sasthyaseba.com/doctors/dr-sankarsan-choudhury : MBBS, MD
https://sasthyaseba.com/doctors/dr-samujjwal-das : BDS, MDS
https://sasthyaseba.com/doctors/dr-asifa-khalid : BDS, Diploma in Endodontics
https://sasthyaseba.com/doctors/dr-dhritiman-mukherjee : BDS, MDS
https://sasthyaseba.com/doctors/ms-sarmistha-sinha-saha : B.Sc, M.Sc
https://sasthyaseba.com/doctors/dr-kausik-kumar-das : MBBS, MS, DNB, MNAMS
https://sasthyaseba.com/doctors/dr-pinak-panikar : BDS, MDS
https://sasthyaseba.com/doctors/dr-boopesh-pugazhendi : MBBS, DNB
https://sasthyaseba.com/doctors/dr-sandeep-kumar-mitra : BDS, MDS
https://sasthyaseba.com/doctors/dr-ranbir-chowdhary : MBBS, MD, MRCP
https://sasthyaseba.com/doctors/dr-roopa-gv : BDS
https://sasthyaseba.com/doctors/dr-ramanuj-ghosh : BDS, MDS, Fellowship in Head & Neck Oncology
https://sasthyaseba.com/doctors/dr-kamlendu-haldar : MBBS, MS, DNB
https://sasthyaseba.com/doctors/dr-pradip-pai-dhungat : MBBS, MD
https://sasthyaseba.com/doctors/dr-samrat-ganguly : BDS
https://sasthyaseba.com/doctors/dr-nidhi-kanchan-nihal : BDS, MDS
https://sasthyaseba.com/doctors/dr-vikram-m-bhardwaj : MBBS, MS, ENT
https://sasthyaseba.com/doctors/dr-rajarshi-bandyopadhyay : BDS, MDS
https://sasthyaseba.com/doctors/dr-pallav-kumar-ghoshal : BDS, MDS
https://sasthyaseba.com/doctors/dr-devaki-thatte-dalvi : MBBS, MD, DNB
https://sasthyaseba.com/doctors/dr-sanjib-chowdhury-5495 : BDS, MDS
https://sasthyaseba.com/doctors/dr-ritoban-saha-bhowmick : BDS, MDS
https://sasthyaseba.com/doctors/dr-sima-datta-ray : MBBS, MD
https://sasthyaseba.com/doctors/dr-swagato-chowdhury : BDS, MDS
https://sasthyaseba.com/doctors/dr-subhas-seth : BDS, MDS
https://sasthyaseba.com/doctors/dr-arindam-mandal : BDS, MDS
https://sasthyaseba.com/doctors/dr-alangkar-saha : BDS, MDS, Fellowship in Head & Neck Oncology
https://sasthyaseba.com/doctors/prof-dr-rakhi-sanyal-dutta-sarma : MBBS, MD, DNB, MNAMS, MRCP, FRCP
https://sasthyaseba.com/doctors/dr-sonia-mary-kurian : MBBS, DCH, DNB, MRCPCH, DAA
https://sasthyaseba.com/doctors/dr-abhik-pyne : BDS, MDS
https://sasthyaseba.com/doctors/dr-m-s-prasad : BDS
https://sasthyaseba.com/doctors/dr-sankarsan-choudhury : BDS, MDS
https://sasthyaseba.com/doctors/dr-bhaskar-reddy-molluru : MBBS, MS (ENT), MRCS, DOHNS, FRCS
https://sasthyaseba.com/doctors/dr-debarghya-chatterjee : MBBS, MD


"""

# Split the string into individual lines and process each line
updates = qualifications_updates_str.strip().split('\n')

updated_count = 0
for entry in updates:
    if entry:
        try:
            url, qualification_str = entry.split(' : ', 1)
            # Update the DataFrame where profile_url matches
            df.loc[df['profile_url'] == url.strip(), 'qualifications'] = qualification_str.strip()
            updated_count += 1
        except ValueError as e:
            print(f"Skipping invalid entry '{entry}': {e}")

print(f"Successfully updated {updated_count} entries for 'qualifications' column.")

# Verify the updates by checking NaN count again
print("\nVerifying NaN count in 'qualifications' after updates:")
nan_count_after_update = df['qualifications'].isnull().sum()
print(f"NaN values in 'qualifications': {nan_count_after_update}")

# 📌 Block: Summary of Every Column (Total Count, Unique Count, NaN Count)

print("📊 COLUMN SUMMARY (ALL COLUMNS)\n")

for col in df.columns:
    total_count = len(df[col])
    unique_count = df[col].nunique(dropna=True)
    nan_count = df[col].isna().sum()

    print("======================================")
    print(f"🔸 COLUMN: {col}")
    print("======================================")
    print(f"📌 Total Values: {total_count}")
    print(f"📌 Unique Values: {unique_count}")
    print(f"📌 NaN / Missing Values: {nan_count}")
    print("\n")

from google.colab import files

output_filename = 'updated_ind_BD_DOC.csv'
df.to_csv(output_filename, index=False)
print(f"DataFrame saved to {output_filename}")

files.download(output_filename)
print(f"You can now download the file: {output_filename}")